alv, pues me falta wex
esto todo weeeeeeeeeeeeeeeeeee

https://dashboard.heroku.com
- create new app "name"
- heroku-login

create database 

ACtividad logica de como trabajar local_settings
configuracion de la rasp_settings.py
con distribucion linux y crear otra configuracion.
crear un archivo .env (archivo oculto)
que un proyecto individual pueda estar en heroku.
y en la raspberry "enviar url" para el lunes, con las credenciales 
para provar que si funciona.

Modelos: 

-python manage.py startapp Example
crear dos archivos:
- urls.py
- serializer.py
        - from rest_framework import routers, serializers, viewsets
        agregando Modelos
        - from example.models import Example

        - class ExampleSerealizer(serializers.ModelSerializer):
            class Meta:
                model = Example
                fields = ('__all__')#obtiene toda la informacion de la que queremos traer a esta clase meta hijo de tu puta madre estoy mamadisimo.
                }


        Views: 
            from django.shortcuts import get_object_or_404
            from django.http import Http404
            from rest_framework.views import APIView
            from rest_framework.response import Response
            from rest_framework import status
            from rest_framework import generics

            from example.models import Example
            from example.serializer import ExampleSerealizer


            class ExampleList(APIView):
                METODO GET PARA SOLICITAR informacion
                def get(self, request, format=None):
                    queryset = Example.objects.filter(delete=False)}
                    serializer = ExampleSerealizer(queryset)
                    return Response(serializer.data)


        urls.py:
            
